# This is a basic workflow to help you get started with Actions

name: test-and-build

on:
  push:
    branches:
      - main

env:
  flutter_version: "3.0.5"
  java_version: "12.x"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./motamot

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r24
      - name: Build NDK 
        runs: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
          cache: true
          cache-key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }} # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64

      - name: Flutter version
        run: flutter --version
      
      - name: Load dependencies
        run: flutter pub get
      
      # Bundle app
      - name: Run tests
        run: flutter test

      # Bundle app
      - name: Bundle App
        run: flutter build appbundle

      